feat(lytfs): allow use of env var to auth requests
jo3-l/yagfuncdata pull request #2
Opened 2023-10-03 10:22 UTC by l-zeuch

This is a combination of two commits:
- chore(deps): upgrade google/go-github to v55
- feat(lytfs): allow use of env var to auth requests

chore(deps:) upgrade google/go-github to v55

  Upgrade google/go-github to v55 (latest), so that the WithAuthToken
  configurator becomes available for us to use.
  
  Additionally this will get rid of the transient dependency on
  "golang.org/x/auth/oauth2", but that is tangential.
  
  Signed-off-By: Luca Zeuch <l-zeuch@email.de>

feat(lytfs): allow use of env var to auth requests

  Allow passing along an environment variable to authenticate requests to
  the GitHub API so that clients have a higher ratelimit.
  
  This is useful for developers wanting to use yagfuncdata, as often
  enough it is just not possible to do so without rapid testing.
  
  Closes #1
  
  Signed-off-by Luca Zeuch <l-zeuch@email.de>

2023-10-03 10:23 UTC, l-zeuch commented on cmd/lytfs/main.go
> +To authenticate your requests, pass a GitHub personal access token via the YAGFUNCDATA_AUTH_TOKEN environment variable.`)
This phrasing is obviously up for debate, but it gets the point across.

2023-10-05 00:06 UTC, jo3-l requested changes
Having `NewGithubClient` change behavior depending on the presence of an environment variable is surprising IMO; that should be done by the program that uses `yagfuncdata`. So WDYT about leaving `DefaultFileContentProvider` as is and instead changing `lytfs` to call `NewGitHubFileProvider` with an authenticated GitHub client if needed?

2023-10-07 02:40 UTC, jo3-l commented on cmd/lytfs/main.go
> +	}
This is a nit, but I would rather write
```suggestion
	fcp := yagpdbfundata.DefaultFileContentProvider
	if token := os.Getenv("YAGFUNCDATA_AUTH_TOKEN"); token != "" {
		fcp = yagfuncdata.NewGitHubFileProvider(github.NewClient(nil).WithAuthToken(token), "botlabs-gg", "yagpdb", "master")
	}
	sources := yagfuncdata.DefaultSources(fcp)
```

2023-10-07 06:29 UTC, l-zeuch commented on cmd/lytfs/main.go
> +	}
Sure, that reads cleaner anyway.

2023-10-07 06:42 UTC, jo3-l approved these changes
LGTM, thanks for your patience :-)

2023-10-07 06:42 UTC, merged

2023-10-07 06:43 UTC, l-zeuch commented
Thanks, no worries :D